#! /usr/bin/env bash

if [ ! -d ./bin ]; then
	echo "[INFO] no './bin' directory"
	echo -n "[INFO] "
	mkdir -v ./bin
fi

fname="multi-type-objects-test"

echo -n "[INFO] compiling ..."
gcc -o ./bin/${fname} *.c && \
echo " done."
echo "[INFO] running ..."
	./bin/${fname}

